### ISSUE TITLE
Home: FAQ: What can I use Zinc for?

### ISSUE THREAD

**Issue by prabhatsharma** [zinclabs/zincsearch-website#8]
Current

What can I use Zinc for?

Zinc is a search engine that can be used for any kind of text data. It can be used for logs, metrics, events, and more. It allows you to do full text search among other things. e.g. Send server logs to Zinc and search for them or you can push your application data and provide full text search.

Required

What can I use ZincSearch for?

ZincSearch is a search engine that can be used for indexing any kind of textual data. It can be used for logs, metrics, events, and more. It allows you to do full text search among other things. e.g. Send server logs to ZincSearch and search for them or you can push your application data and provide full text search in your app.

**Comment by vp2890** [comment]
Fixed

**Comment by prabhatsharma** [comment]
ZincSearch is a search engine that can be used for indexing any kind of textual data. It can be used for logs, metrics, events, and more. It allows you to do full text search among other things. e.g. Send server logs to ZincSearch and search for them or you can push your application data and provide full text search in your app.

is still not fixed

**Comment by vp2890** [comment]
Fixed
